CPP = syclcc
CPP_FLAGS = -O2 --hipsycl-platform=cuda --hipsycl-gpu-arch=sm_61 --cuda-path=/opt/cuda/10.0 -L /opt/cuda/10.0/lib64 -v

BUILD_DIR=build-hipsycl

SYCL_SOURCES = $(wildcard *.cxx)
EXES = $(addprefix $(BUILD_DIR)/,$(basename $(SYCL_SOURCES)))

.PHONY: all
all: $(EXES)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(BUILD_DIR)/% : %.cxx | $(BUILD_DIR)
	@echo "Compiling "$<
	$(CPP) $(CPP_FLAGS) -std=c++17 -o $@ $<


.PHONY: clean
clean:
	rm -r $(BUILD_DIR)/*
