COMPUTE_CPP=/opt/ComputeCpp-CE
INCLUDES=-I$(COMPUTE_CPP)/include
LIBS=-L$(COMPUTE_CPP)/lib -lComputeCpp

CPP = compute++
CPP_FLAGS = -std=c++14

BUILD_DIR=build-computecpp

SYCL_SOURCES = $(wildcard *.cxx)
EXES = $(addprefix $(BUILD_DIR)/,$(basename $(SYCL_SOURCES)))

.PHONY: all
all: $(EXES)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(BUILD_DIR)/% : %.cxx | $(BUILD_DIR)
	@echo "Compiling "$<
	$(CPP) $(CPP_FLAGS) $(INCLUDES) $(LIBS) -o $@ $<

.PHONY: clean
clean:
	rm -rf $(BUILD_DIR)/*
