CPP = syclcc-clang
CPP_FLAGS = -O2 --hipsycl-platform=cuda --hipsycl-gpu-arch=sm_70

BUILD_DIR=build-hipsycl-cuda

SYCL_SOURCES = listdev.cxx gpuinfo.cxx simplebuffer.cxx
EXES = $(addprefix $(BUILD_DIR)/,$(basename $(SYCL_SOURCES)))

.PHONY: all
all: $(EXES)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(BUILD_DIR)/% : %.cxx | $(BUILD_DIR)
	@echo "Compiling "$<
	$(CPP) $(CPP_FLAGS) -std=c++17 -o $@ $<


.PHONY: clean
clean:
	rm -rf $(BUILD_DIR)/*
