name: C/C++ CI CPU

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-sycl:
    runs-on: ubuntu-latest
    #container: intel/oneapi-basekit:devel-ubuntu18.04
    container: ubuntu:18.04
    env:
      ONEAPI_ROOT: /opt/intel/oneapi
      INTEL_LICENSE_FILE: /opt/intel/oneapi/compiler/latest/licensing
      LD_LIBRARY_PATH: /opt/intel/oneapi/compiler/latest/linux/lib:/opt/intel/oneapi/compiler/latest/linux/lib/x64:/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/compiler/latest/linux/compiler/lib:/opt/intel/oneapi/ccl/2021.1-beta09/lib/cpu_gpu_dpcpp

    steps:
    - name: install core packages
      run: apt-get update -y && apt-get install -y wget git build-essential gnupg
    - name: setup oneapi repos
      run: |
        wget -O - 'https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB' | apt-key add -
        echo "deb https://apt.repos.intel.com/oneapi all main" > /etc/apt/sources.list.d/oneAPI.list
        echo 'deb [trusted=yes arch=amd64] https://repositories.intel.com/graphics/ubuntu bionic-devel main' > /etc/apt/sources.list.d/intel-graphics.list
        apt-get update -y
    - name: install dpcpp
      run: apt-get install -y intel-oneapi-dpcpp-cpp-compiler-2021.1-beta09 clinfo intel-opencl intel-level-zero-gpu level-zero
    - uses: actions/checkout@v2
    - name: clinfo
      run: |
        mkdir -p /etc/OpenCL/vendors
        echo "libintelocl.so" > /etc/OpenCL/vendors/intel-cpu.icd
        clinfo
    - name: make
      run: make
    - name: run listdev
      run: ./build-intelone/listdev
    - name: run simplebuffer
      run: ./build-intelone/simplebuffer
    - name: run expr
      run: ./build-intelone/expr
    - name: run usmmem
      run: ./build-intelone/usmmem
    - name: run complex
      run: ./build-intelone/complex
